#!/bin/bash

SCRIPT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
INSTALL_PATH="$HOME/.local/share/nvim/site/pack/packer/start"

# Link config 
rm -rf ~/.config/nvim
ln -s $SCRIPT_PATH ~/.config/nvim

# Install packer (package manager)
rm -rf $INSTALL_PATH/packer.nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim $INSTALL_PATH/packer.nvim

# Install editorconfig (detect editor preferences)
rm -rf $INSTALL_PATH/editorconfig.nvim
git clone --depth 1 https://github.com/gpanders/editorconfig.nvim $INSTALL_PATH/editorconfig.nvim